---
title: "week2_exercise"
output: html_document
date: '2022-04-29'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)        # to import tabular data (e.g. csv)
library(dplyr)        # to manipulate (tabular) data
library(ggplot2)      # to visualize data
library(sf)           # to handle spatial vector data
library(terra)        # To handle raster data
library(lubridate)    # To handle dates and times
```

```{r}
wildschwein_BE <- read_delim("wildschwein_BE_2056.csv",",") 

wildschwein_BE <- st_as_sf(wildschwein_BE, coords = c("E", "N"), crs = 2056, remove = FALSE)
```

Task 2: Getting an overview
```{r}
wildschwein_BE <- group_by(wildschwein_BE, TierID)
wildschwein_BE <- mutate(wildschwein_BE,timelag = as.integer(difftime(lead(DatetimeUTC),DatetimeUTC, units = "secs")))

wildschwein_BE
```


```{r}
ggplot(data = wildschwein_BE) +
  stat_summary(
    mapping = aes(x = DatetimeUTC, y = TierID),
    fun.min = min,
    fun.max = max,
    fun = median) +
  ggtitle("How many individuals were tracked?")
```
Three individuals were tracked Sabi, Rosa and Ruth.The plot shows for how long they were tracked.

```{r}
ggplot(wildschwein_BE, aes(timelag)) +
  geom_bar(stat = "count") +
  xlim(0,1000) +
  ylim(0,1000) 

```
All individuals were tracked more or less concurrently and sometimes sequentially.

```{r}
ggplot(wildschwein_BE, aes(x= wildschwein_BE$DatetimeUTC, y= wildschwein_BE$timelag)) +
  geom_point(color=wildschwein_BE$TierID) + 
  geom_segment( aes(x= DatetimeUTC, xend= DatetimeUTC, y=0, yend= timelag, color = wildschwein_BE$TierID),
                color=wildschwein_BE$TierID) +
  ylim(0,30000) +
  labs(x="Date Time UTC", y="Timelag(sec)", color = "Tier ID")

#I tried to add a Color Legend with the TierID here. Unfortunately, I don't really get it how I have to do it.

```

Task 3:
```{r}
wildschwein_BE <- mutate(wildschwein_BE,steplength = as.integer(sqrt((E-lead(E))^2 + (N-lead(N))^2)))

```

```{r}
wildschwein_BE <- mutate(wildschwein_BE, speed = (steplength/timelag))
```

Task 4:
```{r}
caro <- read_delim("caro60.csv",",") 
caro <- st_as_sf(caro, coords = c("E", "N"), crs = 2056, remove = FALSE)
```

```{r}
caro_3 = caro[seq(1, nrow(caro), 3), ]
caro_6 = caro[seq(1, nrow(caro), 6), ]
caro_9 = caro[seq(1, nrow(caro), 9), ]

nrow(caro)
nrow(caro_3)
nrow(caro_6)
nrow(caro_9)
```

Calculating timelag for all the datasets:
```{r}
caro <- group_by(caro, TierID)
caro <- mutate(caro,timelag = as.integer(difftime(lead(DatetimeUTC), DatetimeUTC, units = "secs")))

caro_3 <- group_by(caro_3, TierID)
caro_3 <- mutate(caro_3,timelag = as.integer(difftime(lead(DatetimeUTC),DatetimeUTC, units = "secs")))

caro_6 <- group_by(caro_6, TierID)
caro_6 <- mutate(caro_6,timelag = as.integer(difftime(lead(DatetimeUTC),DatetimeUTC, units = "secs")))

caro_9 <- group_by(caro_9, TierID)
caro_9 <- mutate(caro_9,timelag = as.integer(difftime(lead(DatetimeUTC),DatetimeUTC, units = "secs")))
```

Calculating step length for all the data sets:
```{r}
caro <- mutate(caro,steplength = (sqrt((E-lead(E))^2 + (N-lead(N))^2)))

caro_3 <- mutate(caro_3,steplength = (sqrt((E-lead(E))^2 + (N-lead(N))^2)))

caro_6 <- mutate(caro_6,steplength = (sqrt((E-lead(E))^2 + (N-lead(N))^2)))

caro_9 <- mutate(caro_9,steplength = (sqrt((E-lead(E))^2 + (N-lead(N))^2)))
```

Calculating speed for all data sets:
```{r}
caro <- mutate(caro, speed = (steplength/timelag))

caro_3 <- mutate(caro_3, speed = (steplength/timelag))

caro_6 <- mutate(caro_6, speed = (steplength/timelag))

caro_9 <- mutate(caro_9, speed = (steplength/timelag))
```

